version: "3.9"
services:
  #####################
  # PostgreSQL Database
  ####################
  database:
    image: postgres:15.2-alpine
    restart: always
    volumes: 
      - ./init:/docker-entrypoint-initdb.d # Mutliple databases in one container
                                           # Ref: https://hub.docker.com/_/postgres/ (Initialization scripts)
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    expose:
      - 5432

  ##########
  # PgAdmin 
  ##########
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8080:80
    depends_on:
      - database

  ############################
  # Prefect Server API and UI
  ###########################
  server:
    image: prefecthq/prefect:2.10.4-python3.11
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["prefect", "server", "start"]
    environment:
      # If you want to access Prefect Server from anywhere other than the Docker host machine, you will need to change
      # PREFECT_UI_URL to match the external hostname/IP used to load the  UI in your web browser.
      - PREFECT_UI_URL=http://127.0.0.0:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect
    ports:
      - 4200:4200
    depends_on:
      - database

  ##################
  # Prefect Agent
  ##################
  agent:
    # image: prefecthq/prefect:2.10.4-python3.11
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    entrypoint: ["prefect", "agent", "start", "-q", "default"]
    volumes:
      - ./flows:/root/flows
      - prefect:/root/.prefect
    environment:
      - PREFECT_API_URL=http://server:4200/api
#       Use PREFECT_API_KEY if connecting the agent to Prefect Cloud
#     - PREFECT_API_KEY=YOUR_API_KEY


  ###############
  # Prefect CLI 
  ###############
  cli:
    # image: prefecthq/prefect:2.10.4-python3.11
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "bash"
    working_dir: "/root/flows"
    volumes:
      - "./flows:/root/flows"
      - "prefect:/root/.prefect"
    environment:
      - PREFECT_API_URL=http://server:4200/api
#       Use PREFECT_API_KEY to use the CLI to interact with Prefect Cloud
#     - PREFECT_API_KEY=YOUR_API_KEY

  ################
  # Chrome Driver
  ################
  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    privileged: true
    shm_size: 2g
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true #Multisession
      - SE_NODE_MAX_SESSIONS=2
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - '4444:4444'

# VOLUMES
volumes:
  # For prefect data, flows, deploys, etc.
  prefect:
  # For project data.
  db:

# NETWORKS
networks:
  default:
    name: prefect-network